services:
  web:
    build: .
    container_name: lab-status
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - NETBOX_URL
      - NETBOX_TOKEN
      - PROXMOX_URL
      - PROXMOX_TOKEN
      - SERVICE_STATUS_URL
      - CONTAINER_STATUS_URL
