services:
  web:
    build:
      context: .
      args:
        - VITE_STATUS_URL
    container_name: lab-status
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - NETBOX_URL
      - NETBOX_TOKEN
